name: bmcs_env
channels:
- conda-forge
dependencies:
- appmode
- jupyter_contrib_nbextensions
- traits>=6.1.1
- matplotlib-base==3.4.3
- numpy
- sympy
- k3d
- ipywidgets==7.6.6
- ipympl==0.9.2
- ipytree==0.2.2
- ipyregulartable
- pip
- pip:
  - -e .
